name: p2juegosmoviles
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1

  sqflite: ^2.3.3+1
  path: ^1.9.0
  crypto: ^3.0.3

  sqflite_common_ffi: ^2.3.3
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/OpenDyslexic-Regularr.otf
        - asset: assets/OpenDyslexic-Boldd.otf
          weight: 500

  assets:
    - assets/
    - assets/musica.mp3

flutter_icons:
  android: true
  ios: true

  image_path: "assets/DJ_Wordle.png"

  adaptive_icon_background: "#C6A4FE"
  adaptive_icon_foreground: "assets/DJ_Wordle.png"